spring:
  application:
    name: item-service

server:
  port: 8001
  
eureka:
  client:
    service-url:
      #默认地点,要由公共云服务来提供
      #如果是私有服务器,必须写defaultZone
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka